theme: jekyll-theme-architect
title: Nautical Calculator for Android
description: Solve many of the marine navigation equations and conversions
show_downloads: false
site.github.is_user_page: false
page.title: Nautical Calculator for Android
