theme: jekyll-theme-architect
title: Nautical Calculator for Android
description: Solve many of the marine navigation equations and conversions
defaults:
  - scope:
      path: ""
    values:
      image: logo.png

# Google Analytics
ga_tracking_id: G-E0N27WTK67
