theme: jekyll-theme-architect
title: Nautical Calculator for Android
description: Solve many of the marine navigation equations and conversions

# Google Analytics
google_analytics: 2616254298
gtag: "G-3XB5W3SWPC"
